#+title: Being a full-stack developer
#+date: <2016-07-12>
#+author: Michael Wang

#+BEGIN_PREVIEW
To be a full-stack developer is really a little hard for anyone including myself.

Within coding and design, even documentation are my main job everyday. Compare to coding, design and documentation use more time. Customers care more about these two part even more than user experience which is combined by those three(the one i thought was most important in any software/system) was dismissed most of time.

After my Objective-C, Php, Ruby on Rails, Html5, css, Javescript and etc, I was focus on [[http://www.filemaker.com][FileMaker]] in past two years as a small business.
#+END_PREVIEW

To be a full-stack developer is really a little hard for anyone including myself.

Within coding and design, even documentation are my main job everyday. Compare to coding, design and documentation use more time. Customers care more about these two part even more than user experience which is combined by those three(the one i thought was most important in any software/system) was dismissed most of time.

After my Objective-C, Php, Ruby on Rails, Html5, css, Javescript and etc, I was focus on [[http://www.filemaker.com][FileMaker]] in past two years as a small business.

*Let's talk about it,*

I have to say it is a wired way to do a solution although it sometimes fast than traditional development.

During using /[[http://www.filemaker.com/][FileMaker]]/ these years, it really important to find out it's global storage type. Generally, it's used as session most time by me. It's like a session and cookies in B/S structure. I use that for remember user's temp variables.

In multi-user environment, it will not saved on server side. Only user can see or change themselves.

Being develop a /[[http://www.filemaker.com][FileMaker]/ solution provider, you have to be a real full-stack developer because it's a little hard to separate design work. In one word, I don't think FileMaker is a good platform for collaboration with mates especially for work remotely.

[[http://www.filemaker.com][FileMaker]] is popular in US, Japan and Australia. United States has biggest market and the 2nd is Japan. I saw a lot of developer from Australia. But since now, FileMaker conference has not held in Australia before.

Fortunately, my company was invited by FileMaker Conference in Japan and US. So let take look at the end of this month of FileMaker Conference on Tokyo.

-----
*Reference:*
- [[http://en.wikipedia.org/wiki/FileMaker][FileMaker on Wikipedia]]
- [[http://en.wikipedia.org/wiki/User_experience][User experience (UX) on Wikipedia]]
- [[http://37signals.com/remote/][Book: Remote: Office Not Required]]
