#+title: I'm back!
#+date: <2016-07-12>
#+author: Michael Wang

#+BEGIN_PREVIEW
So, actually wordpress was blocked for a long time. I have never visit wordpress for THREE years! Although I could jailbreak the [[http://en.wikipedia.org/wiki/Golden_Shield_Project][Chinese Great Firewall]], I do not update this blog any more in last three years.

Just come back and leave some update. and might some useful skill article.
#+END_PREVIEW

So, actually wordpress was blocked for a long time. I have never visit wordpress for THREE years! Although I could jailbreak the [[http://en.wikipedia.org/wiki/Golden_Shield_Project][Chinese Great Firewall]], I do not update this blog any more in last three years.

Just come back and leave some update. and might some useful skill article.

During these three year, I focus on start my own business and pull all my time into learn more in work. At the same time, I get married with Sherry and lucky have a baby this year. Being a father is really a different feeling for me.

Thanks to [[http://shadowsocks.org/en/index.html][Shadowsocks]] let me back to the real international rather than staying in intranet in China.
