#+title: Spotify vs iTunes music
#+date: <2016-07-12 Tue>
#+BEGIN_PREVIEW
Stream music become a controversial topic in social media  after Taylor Swift announce to pull her entire catalog off of Spotify.
#+END_PREVIEW

* Background

Stream music become a controversial topic in social media  after Taylor Swift announce to pull her entire catalog off of Spotify.

** What's next?

I'm not sure when music streaming is get hot. At beginning, [Pandora](http://en.wikipedia.org/wiki/Pandora_Radio "Pandora Radio on Wikipedia") is the first stream-music app as i know. However it is ONLY available in US Apple store, and it could not skip such a lot of ads during enjoying music. This app stay in my iPhone less than half a year.(Although one of the biggest problem is you have to use VPN to pretend you are in US.)

After that i stop using stream-music app for a long time because most of that app has bad network from China. Buffering is annoyed if you are listening music. And for most Chinese, they do not using such Spotify, Pandora, Rdio or other same service. Most my friend could download FREE music in Baidu or Tencent QQ. Those vendor claim that they own the copyright of the songs they offer to download. However, if you trying to get access to [Baidu Music ](http://music.baidu.com "Baidu Music")or [QQ Music](http://y.qq.com/ "QQ Music"), they do not allow to next. You will get a notice like, the service is not provide to your area.

I was being thought as a freak by a lot of my friend because I subscribe Spotify and buy App from App Store and Mac Store for a long time. I do really thought Spotify is really a pretty good service for most people.

As I know, Taylor is not first artist who pull her works off of Spotify. This action make me review what benefit Spotify to us and what benefit it  gives to artists.

Before Spotify, iTunes store probably is biggest music store. The difference is, if you purchase from iTunes, you own the music and you can download it anytime via iTunes or iPhone. Even you can export to AAC/MP3. But in Spotify, you could not own the music. You ONLY have the right to listen the songs.

For listening, iTunes offer 30 seconds free listening at first. Now iTunes offers 90 seconds for users, but if you want full music, you have to pay for that. I could hardly say Spotify has listening before purchase. Spotify limits times of skip during listening and some ads in.

** Finally

The problem is, if you have Spotify Premium account, will you buy any music?

** Reference:
- [[https://www.spotify.com][Spotify]]
- [[http://www.pandora.com/][Pandora Internet Radio]]
- [[http://www.rdio.com/][Rdio]]
